const UPDATE = 'UPDATE';
const DELETE = 'DELETE';
const SET_INITIAL_ERRORS = 'SET_INITIAL_ERRORS';
const RESET = 'RESET';
const UPDATE_FIELD = 'UPDATE_FIELD';
const ADD = 'ADD';

export {UPDATE, DELETE, SET_INITIAL_ERRORS, RESET, UPDATE_FIELD, ADD};
