export type VendorApplicationStatus = "pending" | "approved" | "rejected"

export type VendorApplication = {
  id: string
  businessName: string
  ownerName: string
  location: string
  categories: string[]
  appliedAt: string
  status: VendorApplicationStatus
}

export const vendorApplications: VendorApplication[] = [
  {
    id: "app-1",
    businessName: "SunField Organics",
    ownerName: "Ibrahim Musa",
    location: "Kano",
    categories: ["Vegetable", "Fruits"],
    appliedAt: "Apr 12",
    status: "pending",
  },
  {
    id: "app-2",
    businessName: "Halima R.",
    ownerName: "Ibrahim Musa",
    location: "Plateau",
    categories: ["Fruits"],
    appliedAt: "Apr 11",
    status: "pending",
  },
  {
    id: "app-3",
    businessName: "Grain Co-op",
    ownerName: "Ahmed Lawal",
    location: "Kebbi",
    categories: ["Grains"],
    appliedAt: "Apr 10",
    status: "pending",
  },
  {
    id: "app-4",
    businessName: "GreenField Farm",
    ownerName: "Chioma Adeyemi",
    location: "Kaduna",
    categories: ["Vegetable"],
    appliedAt: "Mar 28",
    status: "approved",
  },
  {
    id: "app-5",
    businessName: "GrainMill Ltd",
    ownerName: "Yusuf Bello",
    location: "Kano",
    categories: ["Grains", "Seeds"],
    appliedAt: "Mar 22",
    status: "approved",
  },
  {
    id: "app-6",
    businessName: "TropicFarm",
    ownerName: "Ngozi Okafor",
    location: "Abuja",
    categories: ["Fruits"],
    appliedAt: "Mar 18",
    status: "approved",
  },
  {
    id: "app-7",
    businessName: "TerraFresh",
    ownerName: "Emeka Nwosu",
    location: "Lagos",
    categories: ["Vegetable", "Herbs"],
    appliedAt: "Mar 15",
    status: "approved",
  },
  {
    id: "app-8",
    businessName: "Harvest Hub",
    ownerName: "Fatima Garba",
    location: "Sokoto",
    categories: ["Grains"],
    appliedAt: "Mar 10",
    status: "approved",
  },
  {
    id: "app-9",
    businessName: "Valley Greens",
    ownerName: "Samuel Eze",
    location: "Enugu",
    categories: ["Vegetable"],
    appliedAt: "Mar 8",
    status: "approved",
  },
  {
    id: "app-10",
    businessName: "Cocoa Collective",
    ownerName: "Amina Hassan",
    location: "Oyo",
    categories: ["Cash Crops"],
    appliedAt: "Mar 5",
    status: "approved",
  },
  {
    id: "app-11",
    businessName: "RiverSide Produce",
    ownerName: "David Okon",
    location: "Cross River",
    categories: ["Fruits", "Vegetable"],
    appliedAt: "Mar 2",
    status: "approved",
  },
  {
    id: "app-12",
    businessName: "Northern Grains Co.",
    ownerName: "Hauwa Ibrahim",
    location: "Borno",
    categories: ["Grains"],
    appliedAt: "Feb 27",
    status: "approved",
  },
  {
    id: "app-13",
    businessName: "Plateau Orchards",
    ownerName: "James Pam",
    location: "Plateau",
    categories: ["Fruits"],
    appliedAt: "Feb 24",
    status: "approved",
  },
  {
    id: "app-14",
    businessName: "Delta Agro",
    ownerName: "Blessing Efe",
    location: "Delta",
    categories: ["Vegetable", "Roots"],
    appliedAt: "Feb 20",
    status: "approved",
  },
  {
    id: "app-15",
    businessName: "Savanna Supply",
    ownerName: "Musa Danjuma",
    location: "Niger",
    categories: ["Grains", "Seeds"],
    appliedAt: "Feb 17",
    status: "approved",
  },
  {
    id: "app-16",
    businessName: "Coastal Farms",
    ownerName: "Grace Akpan",
    location: "Rivers",
    categories: ["Fruits"],
    appliedAt: "Feb 14",
    status: "approved",
  },
  {
    id: "app-17",
    businessName: "Highland Harvest",
    ownerName: "Peter Adamu",
    location: "Benue",
    categories: ["Vegetable", "Grains"],
    appliedAt: "Feb 11",
    status: "approved",
  },
  {
    id: "app-18",
    businessName: "Sunrise Agro Ltd",
    ownerName: "Zainab Aliyu",
    location: "Kwara",
    categories: ["Seeds"],
    appliedAt: "Feb 8",
    status: "approved",
  },
  {
    id: "app-19",
    businessName: "Fresh Roots",
    ownerName: "Tunde Bakare",
    location: "Ogun",
    categories: ["Roots"],
    appliedAt: "Feb 5",
    status: "approved",
  },
  {
    id: "app-20",
    businessName: "AgroLink NG",
    ownerName: "Chidinma Uche",
    location: "Anambra",
    categories: ["Vegetable"],
    appliedAt: "Feb 2",
    status: "approved",
  },
  {
    id: "app-21",
    businessName: "FarmGate Express",
    ownerName: "Kabiru Sule",
    location: "Zamfara",
    categories: ["Grains"],
    appliedAt: "Jan 30",
    status: "approved",
  },
  {
    id: "app-22",
    businessName: "LowYield Farms",
    ownerName: "John Doe",
    location: "Katsina",
    categories: ["Vegetable"],
    appliedAt: "Apr 5",
    status: "rejected",
  },
  {
    id: "app-23",
    businessName: "Incomplete Agro",
    ownerName: "Jane Smith",
    location: "Nasarawa",
    categories: ["Fruits"],
    appliedAt: "Apr 2",
    status: "rejected",
  },
]

export function formatApplicationOwnerLine(application: VendorApplication): string {
  const categoryPart = application.categories.join(" • ")
  return `Owner: ${application.ownerName} • ${application.location} • ${categoryPart}`
}
